[phases.setup]
nixPkgs = ["nodejs_20_11"]

[phases.install]
env = { NPM_CONFIG_PRODUCTION = "false" }
cmds = ["npm ci"]

[phases.build]
env = { NPM_CONFIG_PRODUCTION = "false" }
cmds = ["npm run build"]

[start]
cmd = "npm run start"
