[theme]
primaryColor = "#C1A6FF"
backgroundColor = "#030E19"
secondaryBackgroundColor = "#1A2332"
textColor = "#FFFFFF"
font = "sans serif"

[logger]
level = "info"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
port = 8501
headless = true
runOnSave = true
